spring:
  config:
    import: optional:file:.env.development[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

api:
  security:
    token:
      secret: sptech

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_API_URL}
brevo:
  key: ${BREVO_API_KEY}
  url: ${BREVO_API_URL}
server:
  servlet:
    context-path: /api