spring:
  datasource:
    url: jdbc:mysql://localhost:3307/db_hardwaretech_local
    username: root
    password: h4rdw4reTECH
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: optional:file:.env.development

api:
  security:
    token:
      secret: sptech

gemini:
  api:
    key: AIzaSyBRcSAzqRFt9xofqbE0oYaEml0wIjVvvQY

server:
  servlet:
    context-path: /api